### PR TITLE
Add clearance token and userAgent

### PR DESCRIPTION
**Pull request by mohammad-oghli**
As a temporary workaround to fix the authentication token error we should add clearanceToken and userAgent. I added them as comment in the code.

### CODE REVIEW

**Comment by timkmecl** [comment]
Hi, thank you for letting me know about this! I will update the repo to use the latest version of chatgpt-api that utilizes this in a few hours.

Do you think these two parameters should be a part of extension setting like sessionTokens is now or should there be a popup that opens when the extension is run/tokens expire (since these parameters will have to be updated more often)?

**Comment by mohammad-oghli** [comment]
Your welcome, Yes I think these tow parameters should be a part of extension setting like sessionTokens. Check the updated issue on the [chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api) for additional Cloudflare protections that openAI added it.

**Comment by mohammad-oghli** [comment]
Well done!
I think the issue worked as expected I tested on my VS Code
issue

**Comment by timkmecl** [comment]
Great, I am happy it works! 
I will now close this PR, but thanks again for bringing the issue to my attention and suggesting a solution:)

**Pull request closed without merging**
